export const CART_ACTION_TYPES = {
    TOGGLE_IS_CART_OPEN: "TOGGLE_IS_CART_OPEN",
    SET_CART_ITEMS: "SET_CART_ITEMS",
    // SET_CART_COUNT: "SET_CART_COUNT",
    // SET_TOTAL_COST: "SET_TOTAL_COST",
  };